### ISSUE TITLE
rename Stdlib.Seq into Stdlib.Sequence?

### ISSUE THREAD

**Issue by backtracking** [ocaml-gospel/gospel#115]
to avoid confusion with `Seq` from the OCaml standard library

**Comment by mariojppereira** [comment]
I am tempted to say yes. However, specification can become quite verbose.

On the other hand, do we really need a specific module for sequence operations? I mean, my intuition tells me `seq` would naturally become the "ground" type in our specifications, would it be to bad to make every sequence function top-level in `gospelstdlib` ?

**Comment by backtracking** [comment]
If we have syntax for the most common operations (i.e. `get`, `concat`, `length`), then this is not necessarily a problem to have a `Sequence` module.

**Comment by mariojppereira** [comment]
Since you mentioned syntax, any chances we could have some way to pattern match over sequences? For instance, any simple means to recognize the empty sequence, a singleton sequence, etc? Otherwise, one might be doing a lot of `Sequence.empty`, `Sequence.singleton ...`
