### ISSUE TITLE
Unattached Gospel comment is ignored

### ISSUE THREAD

**Issue by fpottier** [ocaml-gospel/gospel#144]
I note that an unattached Gospel comment, like this, is ignored:
```
(*@ a = make n x
      requires n > 0
      ensures  forall i. a(i) = x *)
```
This seems undesirable: perhaps this comment is unattached by mistake (e.g., due to an unwanted blank line), so we should at least warn about it.

As a particular case, a Gospel comment that appears *in front of* a value declaration is ignored:
```
(*@ a = make n x
      requires n > 0
      ensures  forall i. a(i) = x *)
val make: int -> 'a -> 'a t
```
This seems undesirable; ideally, I think that this Gospel comment should be considered attached to the declaration of `make`.

**Comment by pascutto** [comment]
I cannot seem to reproduce your issue. In both cases, the comments are not ignored and I get an `OCaml syntax error` instead (will answer in #143 about that). Can you give more details on how you get them to be ignored?

> perhaps this comment is unattached by mistake

Surely that's not what's happening. Spec comments that don't start with one of these keywords are always translated by [the preprocessor](https://github.com/ocaml-gospel/gospel/blob/main/src/pps.mll) into attached attributes: `function  type  predicate  axiom  val  open`

**Comment by fpottier** [comment]
OK, sorry, I guess I was confused, I mistakenly thought that a Gospel comment was ignored, and it was not.

I remark that the following is accepted:
```
val make: int -> 'a -> 'a t

(*@ a = make n x
    requires 0 < n
    ensures  forall i. a.view(i) = x *)
val make: 'a t -> int -> 'a

(*@ x = make a i
    requires 0 <= i
    ensures  x = a.view(integer_of_int i) *)
```
This is weird because the *first* comment looks as though it is attached to the *second* declaration of `make`, but the Gospel type-checker considers that it is attached to the *first* declaration of `make`.

**Comment by fpottier** [comment]
(Unlikely to be a problem in practice, but in a case like this, I would prefer the system to tell me that a Gospel comment must come *after* the value declaration, not *before* it.)

**Comment by pascutto** [comment]
> This is weird because the _first_ comment looks as though it is attached to the _second_ declaration of `make`, but the Gospel type-checker considers that it is attached to the _first_ declaration of `make`.

I very much agree with you, the preprocessor can definitely be improved in the case of comments appearing before declarations.
I suggest closing this issue and addressing the preprocessor improvement in #143 instead, if you're fine with it.
