### ISSUE TITLE
Tuples as constructor arguments

### ISSUE THREAD

**Issue by pascutto** [ocaml-gospel/gospel#15]
The type-checker does not currently make any difference between
```ocaml
type t = E of int * int
```
and
```ocaml
type t = E of (int * int)
```
while this difference exists in OCaml.
For instance, it is possible with the latter to write `let x = (1, 2) in E x`, while this is not allowed with the former.
In both cases, this term is allowed in Gospel, which is wrong.

**Comment by n-osborne** [comment]
Does the problem come from [here](https://github.com/ocaml-gospel/gospel/blob/main/src/typing.ml#L495) ?

I don't understand why the list is put in a tuple.

**Comment by pascutto** [comment]
This certainly looks suspicious... There's probably a similar problem happening in the typing (and/or parsing) of patterns too.
