### ISSUE TITLE
Syntax error for `(::)` notation in patterns

### ISSUE THREAD

**Issue by mariojppereira** [ocaml-gospel/gospel#201]
The following piece of code issues a syntax error:
```
  val f : int list -> int
  (*@ r = f l
            requires match l with
                          | _ :: x :: _ :: _ :: _ -> x >= 0
                          | _ -> false *)
```

The reason is that our parser only accepts `pat_uni_` as `(::)` arguments. Thus, one way to fix the above is by doing the following:
```
    val f : int list -> int
  (*@ r = f l
            requires match l with
                          | _ :: (x :: (_ :: (_ :: _ ))) -> x >= 0
                          | _ -> false *)
```

This is tremendously inconvenient.

**Comment by backtracking** [comment]
We have already fixed this with @paulpatault (in a branch still to be merged).

**Comment by pascutto** [comment]
@mariojppereira Could you open a PR adding these as tests so we can detect this if it happens again?

**Comment by pascutto** [comment]
Actually, I think @paulpatault added a test with this already [here](https://github.com/ocaml-gospel/gospel/blob/main/test/patterns/positive/positive-patterns.mli#L139).
Don't hesitate to reopen this if it is not fixed.
