### ISSUE TITLE
Spurious type check error

### ISSUE THREAD

**Issue by paulpatault** [ocaml-gospel/gospel#210]
The `gospel check` command fails on input :
```
val f: int -> (int * int, int) result
(*@ r = f ()
    ensures
      match r with
      | Ok (p, q) -> true
      | _         -> false *)
```

with the following spurious error :
```
Error:
  The constructor `Ok' expects `1' argument(s)
  but is applied to 2 argument(s) here.
```

It may be related to too late instanciation of type variables from `('a*'b) result`.

**Comment by pascutto** [comment]
We should probably stick to the same comvention that OCaml has for the difference between constructors that take a single tuple argument and constructors that take multiple arguments
