### ISSUE TITLE
syntax error in the documentation

### ISSUE THREAD

**Issue by n-osborne** [ocaml-gospel/gospel#250]
While going through the documentation looking for examples with @shym, we've spotted some mistakes (`gospel check` throwing a Syntax Error).

#249 fixes one of them. Another is that in the `Union-find` example, `equivalent` is used to name a predicate though it is a reserved keyword.

These two findings has been done empirically (aka we were lucky to stumble on them). Maybe we should extract the OCaml (and gospel) code of the documentation and check them.

**Comment by mariojppereira** [comment]
Yes, I agree with you. Once we have a good integration with a documentation system, it will be the other way around: write (well-typed) OCaml + Gospel, then produce documentation :)
