### ISSUE TITLE
Bad location for a type error

### ISSUE THREAD

**Issue by shym** [ocaml-gospel/gospel#258]
Given the simple file `ex.mli`:
```
type 'a t
val create: int -> t
```
`gospel check` reports:
```
$ gospel check ex.mli 
File "ex.mli", line 1, characters 8-9:
1 | type 'a t
            ^
Error: The type `t' expects 1 argument(s) but was given 0 argument(s) here.
```

**Comment by pascutto** [comment]
The wrong locations are the ones in `dterm.ml`, [here](https://github.com/ocaml-gospel/gospel/blob/main/src/ttypes.ml#L95-L99) and [here](https://github.com/ocaml-gospel/gospel/blob/main/src/ttypes.ml#L106-L110).
These functions don't have the correct location available (they should!)
