### ISSUE TITLE
Fix on pps for documentation broke location

### ISSUE THREAD

**Issue by n-osborne** [ocaml-gospel/gospel#272]
I've just discovered that #267 broke the location as it turns the documentation comments into documentation attributes that take less lines in the resulting file.

I expect some location annotations should fix them.

Sorry that I merges this PR too early as I needed it for the `ppx_odoc_of_gospel`.

**Comment by jmid** [comment]
No worries, we have all been there! :smiley: 

- Would it make sense to revert the merged PR temporarily?
- What tests should we add to catch this change of behaviour and thus prevent similar changes from going uncaught in the future?

**Comment by n-osborne** [comment]
It would indeed make sense to revert the PR as having the correct locations in the error message from gospel type checker and ortac id more important that having the specifications displayed in odoc generated documentation.

**Comment by n-osborne** [comment]
Closed by #281
