### ISSUE TITLE
Check that the documentation is up to date

### ISSUE THREAD

**Issue by n-osborne** [ocaml-gospel/gospel#293]

**Comment by shym** [comment]
Among other things, we should update information about the various related tools: Ortac has changed quite a lot, in particular.

**Comment by shym** [comment]
It would be a good opportunity to revise its structure, to make it easier for newcomers.
#57 and #322 contain a few ideas.

**Comment by shym** [comment]
Still missing elements in the documentation:
- limitations to the supported language (`include`, for instance, see #302),
- updates to the description of tools.

**Comment by n-osborne** [comment]
Closing as the documentation has been revised intensively.
