### ISSUE TITLE
Allow tuple destruction in anonymous function

### ISSUE THREAD

**Issue by n-osborne** [ocaml-gospel/gospel#296]

**Comment by shym** [comment]
A reasonable implementation would probably use patterns there, as we would want to allow also nested tuples, etc.
But patterns do not parse casts at the moment it seems (and they would be required for function arguments):
```ocaml
val f : int option -> int
(*@ r = f x
    requires match x with
             | Some (y:int) -> y >= 0
             | None -> true *)
```
