### ISSUE TITLE
Why `fs_bool_false` is `False` rather than `false`?

### ISSUE THREAD

**Issue by shym** [ocaml-gospel/gospel#315]
`fs_bool_false` and `fs_bool_true` symbols use capitalized spelling `False` and `True` rather than the standard OCaml booleans. It makes error messages confusing.

Is that another symptom of the confusion between `prop` and `bool` (see #287)?

I propose to use standard spellings.

**Comment by n-osborne** [comment]
I agree.

`fs_bool_*` are boolean Gospel values. Their `prop` counterparts are not symbols in the AST but terms (`Ttrue` and `Tfalse`).
Out of curiosity, do we have an error message where it appears?

**Comment by shym** [comment]
> Out of curiosity, do we have an error message where it appears?

Yes, there are two non-exhaustive tests where they appear. That’s how I realised there was an issue, when cleaning up the tests.
