### ISSUE TITLE
Move the documentation about the attribute syntax to an appendix page

### ISSUE THREAD

**Issue by shym** [ocaml-gospel/gospel#322]
The section “Language specification” of the documentation starts with the explanation of the attribute syntax, etc. which is never used, and is ever used only by Gospel developers, probably.
I suggest moving it to an appendix page.

**Comment by jmid** [comment]
I posted some comments in #57 back in 2021 after having given the documentation a read through - and started with a similar impression! I don't know if the other comments have been addressed.
