### ISSUE TITLE
Publish a full documentation

### ISSUE THREAD

**Issue by pascutto** [ocaml-gospel/gospel#57]
Still to do:
- [x] Finish the mutable queue walk-through
- [x] Finish the union-find walk-through
- [ ] Write a landing page
- [ ] Polish the language specification section
- [x] Finish the FAQ

**Comment by jmid** [comment]
*logical.md*

- 'Uninterpreted symbols and Axioms' is incomplete.
   There is an axiom example in 'Logical function contracts' however, so perhaps a first version can be completed by rearranging it.

- I was missing an explanation of `variant`, e.g.,

	"A `variant` is a termination measure. It has to have type `int`, be non-negative, and decrease strictly on each recursive call. "

  (but this is just me guessing...)
